In [13]:
import numpy as np
import pandas

In [24]:
english = pandas.read_csv("train_cap2018.csv")

english.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>fulltext</th>
      <th>sentences</th>
      <th>words</th>
      <th>letters.all</th>
      <th>syllables</th>
      <th>punct</th>
      <th>avg.sentc.length</th>
      <th>avg.word.length</th>
      <th>avg.syll.word</th>
      <th>sntc.per.word</th>
      <th>...</th>
      <th>Maas lgV0</th>
      <th>MATTR</th>
      <th>MSTTR</th>
      <th>MTLD</th>
      <th>Root TTR</th>
      <th>Summer</th>
      <th>TTR.1</th>
      <th>Uber index</th>
      <th>Yule's K</th>
      <th>level1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>\r\r\n      The Eiffel Tower The Eiffel Tower ...</td>
      <td>16</td>
      <td>233</td>
      <td>1116</td>
      <td>363</td>
      <td>32</td>
      <td>14.562500</td>
      <td>4.789700</td>
      <td>1.557940</td>
      <td>0.068670</td>
      <td>...</td>
      <td>4.96</td>
      <td>0.72</td>
      <td>0.70</td>
      <td>70.74</td>
      <td>8.98</td>
      <td>0.88</td>
      <td>0.59</td>
      <td>24.30</td>
      <td>146.62</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>\r\r\n      The Court Green burglar arrested A...</td>
      <td>7</td>
      <td>180</td>
      <td>866</td>
      <td>268</td>
      <td>18</td>
      <td>25.714286</td>
      <td>4.811111</td>
      <td>1.488889</td>
      <td>0.038889</td>
      <td>...</td>
      <td>5.07</td>
      <td>0.74</td>
      <td>0.76</td>
      <td>107.12</td>
      <td>8.57</td>
      <td>0.89</td>
      <td>0.64</td>
      <td>26.14</td>
      <td>141.98</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>\r\r\n      Thank you for giving us the opport...</td>
      <td>10</td>
      <td>180</td>
      <td>861</td>
      <td>269</td>
      <td>20</td>
      <td>18.000000</td>
      <td>4.783333</td>
      <td>1.494444</td>
      <td>0.055556</td>
      <td>...</td>
      <td>5.99</td>
      <td>0.77</td>
      <td>0.78</td>
      <td>161.93</td>
      <td>9.62</td>
      <td>0.92</td>
      <td>0.72</td>
      <td>35.15</td>
      <td>62.96</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>\r\r\n      The international AI conference ca...</td>
      <td>10</td>
      <td>180</td>
      <td>872</td>
      <td>281</td>
      <td>20</td>
      <td>18.000000</td>
      <td>4.844444</td>
      <td>1.561111</td>
      <td>0.055556</td>
      <td>...</td>
      <td>5.49</td>
      <td>0.77</td>
      <td>0.81</td>
      <td>141.10</td>
      <td>9.09</td>
      <td>0.90</td>
      <td>0.68</td>
      <td>30.11</td>
      <td>70.99</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>\r\r\n      I believe that the creative writin...</td>
      <td>11</td>
      <td>187</td>
      <td>849</td>
      <td>283</td>
      <td>29</td>
      <td>17.000000</td>
      <td>4.540107</td>
      <td>1.513369</td>
      <td>0.058824</td>
      <td>...</td>
      <td>4.61</td>
      <td>0.68</td>
      <td>0.64</td>
      <td>70.69</td>
      <td>7.97</td>
      <td>0.87</td>
      <td>0.58</td>
      <td>22.02</td>
      <td>124.11</td>
      <td>C2</td>
    </tr>
  </tbody>
</table>
<p>5 rows Ã— 60 columns</p>
</div>

In [25]:
col = ['sentences', 'level1']
english = english[col]
english.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>sentences</th>
      <th>level1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>16</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>7</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>10</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>10</td>
      <td>C2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>11</td>
      <td>C2</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
import matplotlib.pyplot as plt
fig = plt.figure()
english.groupby('level1').sentences.count().plot.bar(ylim=0)
plt.show()

NameError: global name '_converter' is not defined